AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  showroom-backend

  Sample SAM Template for showroom-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  ProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.showroom.handler.ProductHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: products

      Events:
        GetProducts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: get

        GetProduct:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: get

        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: post

        UpdateProduct:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: put

        DeleteProduct:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: delete
