name: backend CD

on:
  push:
    tags:
      - "backend-v*.*.*"

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::011422533581:role/showroom-deploy-role
          aws-region: ap-southeast-1
          retry-max-attempts: 1
          action-timeout-s: 30

      - name: Check AWS credentials
        run: aws sts get-caller-identity

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build backend
        run: |
          cd backend/showroom-backend
          sam build

      - name: Deploy backend
        run: |
          cd backend/showroom-backend
          sam deploy \
          --parameter-overrides \
          UserPoolArn="${{ secrets.USER_POOL_ARN }}" \
          --no-confirm-changeset

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
