name: frontend CI

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies frontend
        run: npm ci

      - name: Dependencies security check frontend
        run: npm audit

      - name: Lint code frontend
        run: npm run lint

      - name: Build frontend
        run: npm run build
