name: OIDC Debug

on:
  push:
    branches:
      - fix/debug
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug OIDC
        uses: github/actions-oidc-debugger@main
